server:
  port: 8080

spring:
  application:
    name: order-status-chatbot
  
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: chatbot
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-long-and-secure
  expiration: 86400000 # 24 hours in milliseconds

# OpenAI Configuration
openai:
  api-key: your-openai-api-key-here
  model: gpt-3.5-turbo
  max-tokens: 150
  temperature: 0.7

# Rate Limiting Configuration
rate-limit:
  chat:
    requests-per-minute: 10
  openai:
    requests-per-minute: 50

# Logging Configuration
logging:
  level:
    com.chatbot: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000,https://*.railway.internal,https://*.railway.app,https://chatbot-challenge-production-03c8.up.railway.app"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.chatbot.controller
  paths-to-match: /api/** 