-- RAG Database Initialization Script
-- This script sets up the database for RAG (Retrieval-Augmented Generation) functionality

-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Create knowledge_base table for storing document embeddings
CREATE TABLE IF NOT EXISTS knowledge_base (
    id BIGSERIAL PRIMARY KEY,
    document_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    tags TEXT, -- JSON array as string
    embedding TEXT, -- Store JSON string
    embedding_vector vector(1536), -- Vector for similarity search
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_knowledge_base_document_id ON knowledge_base(document_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_category ON knowledge_base(category);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_embedding_vector ON knowledge_base USING ivfflat (embedding_vector vector_cosine_ops) WITH (lists = 100);

-- Create function to update updated_date automatically
CREATE OR REPLACE FUNCTION update_updated_date_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_date
CREATE TRIGGER update_knowledge_base_updated_date 
    BEFORE UPDATE ON knowledge_base 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_date_column();

-- Create function to convert JSON string to vector
CREATE OR REPLACE FUNCTION json_to_vector(json_text TEXT)
RETURNS vector AS $$
DECLARE
    vector_array FLOAT[];
    json_array JSONB;
BEGIN
    json_array := json_text::JSONB;
    SELECT array_agg(value::FLOAT) INTO vector_array
    FROM jsonb_array_elements(json_array);
    RETURN vector_array::vector;
END;
$$ LANGUAGE plpgsql;

-- Insert sample knowledge base documents (these will be replaced by the application)
-- Note: Embeddings will be generated by the application using OpenAI

-- Sample document 1: Order Status Overview
INSERT INTO knowledge_base (document_id, title, content, category, tags, created_date) VALUES
('order-status-overview', 'Order Status Overview', 
'Order status represents the current state of a customer''s order in the fulfillment process. Each order goes through a series of status transitions from creation to delivery. Understanding order statuses helps customers track their purchases and know when to expect their items. The main order statuses include: PENDING (order received, payment processing), PROCESSING (order confirmed, being prepared), SHIPPED (order dispatched, in transit), DELIVERED (order received by customer), CANCELLED (order cancelled), and REFUNDED (order returned and refunded). Each status has specific implications for delivery timeframes and customer expectations.',
'order-management', '["order-status", "fulfillment", "tracking", "customer-service"]', CURRENT_TIMESTAMP)
ON CONFLICT (document_id) DO NOTHING;

-- Sample document 2: Status Transitions
INSERT INTO knowledge_base (document_id, title, content, category, tags, created_date) VALUES
('status-transitions', 'Order Status Transitions',
'Order status transitions follow a specific flow: PENDING → PROCESSING → SHIPPED → DELIVERED. PENDING status occurs when an order is first placed and payment is being processed. This typically takes 1-2 business days. PROCESSING status indicates the order has been confirmed and is being prepared for shipment, including inventory allocation and packaging. This usually takes 2-3 business days. SHIPPED status means the order has been dispatched and is in transit to the customer. Delivery time depends on shipping method: standard (5-7 business days), express (2-3 business days), or overnight (1 business day). DELIVERED status confirms the order has been received by the customer. Additional statuses include CANCELLED (order cancelled before shipment) and REFUNDED (order returned and refund processed). Customers can track their order status through their account or by contacting customer service.',
'order-management', '["status-transitions", "fulfillment-process", "delivery-timeline", "tracking"]', CURRENT_TIMESTAMP)
ON CONFLICT (document_id) DO NOTHING;

-- Sample document 3: Fulfillment Workflow
INSERT INTO knowledge_base (document_id, title, content, category, tags, created_date) VALUES
('fulfillment-workflow', 'Fulfillment Workflow',
'The fulfillment workflow consists of several stages: Order Receipt, Payment Processing, Inventory Allocation, Picking and Packing, Shipping, and Delivery. Order Receipt occurs when a customer places an order through the website or mobile app. Payment Processing involves verifying payment and authorizing the transaction, which typically takes 1-2 business days. Inventory Allocation ensures the ordered items are available and reserved for the customer. Picking and Packing involves warehouse staff selecting the items and preparing them for shipment with proper packaging and labeling. Shipping includes generating shipping labels, coordinating with carriers, and tracking the package. Delivery is the final stage where the package reaches the customer. The entire fulfillment process typically takes 7-14 business days for standard shipping, with expedited options available for faster delivery. Quality control checks are performed at each stage to ensure customer satisfaction.',
'fulfillment', '["fulfillment", "warehouse", "shipping", "delivery", "process"]', CURRENT_TIMESTAMP)
ON CONFLICT (document_id) DO NOTHING;

-- Sample document 4: API Documentation - Get Order Status
INSERT INTO knowledge_base (document_id, title, content, category, tags, created_date) VALUES
('api-get-order-status', 'Get Order Status API',
'The GET /api/orders/{orderNumber} endpoint retrieves detailed information about a specific order. The endpoint accepts an order number as a path parameter and returns order details including status, customer information, shipping address, total amount, and timestamps. Response includes: order ID, order number, customer ID, current status (PENDING, PROCESSING, SHIPPED, DELIVERED, CANCELLED, REFUNDED), total amount, shipping address, created date, and updated date. If the order is not found, the API returns a 404 status code with an appropriate error message. The endpoint requires authentication via JWT token in the Authorization header. Example successful response: { ''id'': 1, ''orderNumber'': ''ORD-001'', ''customerId'': 1, ''status'': ''SHIPPED'', ''totalAmount'': 299.99, ''shippingAddress'': ''123 Main St, New York, NY 10001'', ''createdDate'': ''2024-01-15T10:30:00'', ''updatedDate'': ''2024-01-19T14:45:00'' }. Example error response: { ''error'': ''Order not found'', ''timestamp'': ''2024-01-20T10:30:00'', ''status'': 404 }.',
'api-documentation', '["api", "order-status", "endpoint", "rest", "get-order"]', CURRENT_TIMESTAMP)
ON CONFLICT (document_id) DO NOTHING;

-- Sample document 5: Shipping Methods
INSERT INTO knowledge_base (document_id, title, content, category, tags, created_date) VALUES
('shipping-methods', 'Shipping Methods and Delivery Options',
'We offer three main shipping methods: Standard Shipping (5-7 business days), Express Shipping (2-3 business days), and Overnight Shipping (1 business day). Standard shipping is free for orders over $50, otherwise $5.99. Express shipping costs $12.99 and includes package tracking. Overnight shipping costs $24.99 and guarantees next business day delivery. All shipping methods include package tracking and insurance. Delivery times are estimates and may vary based on destination and carrier availability. International shipping is available to select countries with delivery times of 7-14 business days. Shipping costs are calculated based on order weight, destination, and selected method. Customers can track their packages using the tracking number provided in their order confirmation email or through their account dashboard. Delivery attempts are made during business hours, and packages may be left with a neighbor or at a local post office if no one is available to receive them.',
'shipping', '["shipping", "delivery", "tracking", "carriers", "costs"]', CURRENT_TIMESTAMP)
ON CONFLICT (document_id) DO NOTHING;

-- Log completion
DO $$
BEGIN
    RAISE NOTICE 'RAG database initialization completed successfully';
    RAISE NOTICE 'pgvector extension enabled';
    RAISE NOTICE 'knowledge_base table created with indexes';
    RAISE NOTICE 'Sample documents inserted';
END $$; 